name: CI
on:
  push:
  schedule:
    - cron: '*/20 * * * *'
    
jobs:
  weather_job:
    name: gether weather
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash ./SendMail.sh
      - name: 'echo data'
        run: echo "good boy!" >> 1.txt
  mail_job:
    name: send mail
    needs: weather_job
    runs-on: ubuntu-latest
    steps:
      - name: 'Get Date'
        run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash ./SendMail.sh
      - name: 'echo Weather'
        run: cat ./result.html
        
      - name: get mail address
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Shanghai Weather Report (${{env.REPORT_DATE}})
          #body: Build job of ${{github.repository}} completed successfully!
          body: file://result.html
          to: bigdot123456@qq.com;cn.bigdot@gmail.com
          from: GitHub Actions
          content_type: text/html
  echo_job:
    name: echo Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
      

 
